export declare const paths: {
  "MaterialIcons-Regular.codepoints": string;
  "MaterialIcons-Regular.ttf": string;
  "MaterialIcons-Regular.woff": string;
  "MaterialIcons-Regular.woff2": string;
  "MaterialIconsOutlined-Regular.codepoints": string;
  "MaterialIconsOutlined-Regular.otf": string;
  "MaterialIconsOutlined-Regular.woff": string;
  "MaterialIconsOutlined-Regular.woff2": string;
  "MaterialIconsRound-Regular.codepoints": string;
  "MaterialIconsRound-Regular.otf": string;
  "MaterialIconsRound-Regular.woff": string;
  "MaterialIconsRound-Regular.woff2": string;
  "MaterialIconsSharp-Regular.codepoints": string;
  "MaterialIconsSharp-Regular.otf": string;
  "MaterialIconsSharp-Regular.woff": string;
  "MaterialIconsSharp-Regular.woff2": string;
  "MaterialIconsTwoTone-Regular.codepoints": string;
  "MaterialIconsTwoTone-Regular.otf": string;
  "MaterialIconsTwoTone-Regular.woff": string;
  "MaterialIconsTwoTone-Regular.woff2": string;
};
export { default as materialIconsOutlinedRegularCodepoints } from "./materialIconsOutlinedRegularCodepoints";
export { default as materialIconsOutlinedRegularLigatures } from "./materialIconsOutlinedRegularLigatures";
export { default as materialIconsOutlinedRegularOtf } from "./materialIconsOutlinedRegularOtf";
export { default as materialIconsOutlinedRegularWoff } from "./materialIconsOutlinedRegularWoff";
export { default as materialIconsOutlinedRegularWoff2 } from "./materialIconsOutlinedRegularWoff2";
export { default as materialIconsRegularCodepoints } from "./materialIconsRegularCodepoints";
export { default as materialIconsRegularLigatures } from "./materialIconsRegularLigatures";
export { default as materialIconsRegularTtf } from "./materialIconsRegularTtf";
export { default as materialIconsRegularWoff } from "./materialIconsRegularWoff";
export { default as materialIconsRegularWoff2 } from "./materialIconsRegularWoff2";
export { default as materialIconsRoundRegularCodepoints } from "./materialIconsRoundRegularCodepoints";
export { default as materialIconsRoundRegularLigatures } from "./materialIconsRoundRegularLigatures";
export { default as materialIconsRoundRegularOtf } from "./materialIconsRoundRegularOtf";
export { default as materialIconsRoundRegularWoff } from "./materialIconsRoundRegularWoff";
export { default as materialIconsRoundRegularWoff2 } from "./materialIconsRoundRegularWoff2";
export { default as materialIconsSharpRegularCodepoints } from "./materialIconsSharpRegularCodepoints";
export { default as materialIconsSharpRegularLigatures } from "./materialIconsSharpRegularLigatures";
export { default as materialIconsSharpRegularOtf } from "./materialIconsSharpRegularOtf";
export { default as materialIconsSharpRegularWoff } from "./materialIconsSharpRegularWoff";
export { default as materialIconsSharpRegularWoff2 } from "./materialIconsSharpRegularWoff2";
export { default as materialIconsTwoToneRegularCodepoints } from "./materialIconsTwoToneRegularCodepoints";
export { default as materialIconsTwoToneRegularLigatures } from "./materialIconsTwoToneRegularLigatures";
export { default as materialIconsTwoToneRegularOtf } from "./materialIconsTwoToneRegularOtf";
export { default as materialIconsTwoToneRegularWoff } from "./materialIconsTwoToneRegularWoff";
export { default as materialIconsTwoToneRegularWoff2 } from "./materialIconsTwoToneRegularWoff2";
